1. pom.xml

<distributionManagement>
  <repository>
    <id>nexus-releases</id>
    <url>https://nexus.company.com/repository/maven-releases/</url>
  </repository>
  <snapshotRepository>
    <id>nexus-snapshots</id>
    <url>https://nexus.company.com/repository/maven-snapshots/</url>
  </snapshotRepository>
</distributionManagement>

2. 

name: Java Library CI - Nexus

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version"
        type: string
        default: "17"
      release-branch:
        description: "Release branch"
        type: string
        default: "main"
      snapshot-branch:
        description: "Snapshot branch"
        type: string
        default: "develop"
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
              <server>
                <id>nexus-snapshots</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build & Test
        run: mvn clean verify

      # Safety guard: no SNAPSHOT allowed on release branch
      - name: Block SNAPSHOT on release branch
        if: github.ref_name == inputs.release-branch
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Version: $VERSION"
          if [[ "$VERSION" == *SNAPSHOT ]]; then
            echo "❌ SNAPSHOT version not allowed on release branch"
            exit 1
          fi

      - name: Deploy to Nexus
        if: |
          github.ref_name == inputs.release-branch ||
          github.ref_name == inputs.snapshot-branch
        run: mvn deploy -DskipTests


- name: Publish summary
  if: |
    github.ref_name == inputs.release-branch ||
    github.ref_name == inputs.snapshot-branch
  run: |
    NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

    {
      echo "## 🚀 Nexus Publish Summary"
      echo ""
      echo "**Library** : \`$NAME\`"
      echo "**Version** : \`$VERSION\`"
      echo "**Branch**  : \`${{ github.ref_name }}\`"
      echo ""
      echo "Artifact successfully published to Nexus."
    } >> "$GITHUB_STEP_SUMMARY"


- name: Enforce branch–version policy
  shell: bash
  run: |
    VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    BRANCH="${{ github.ref_name }}"
    RELEASE_BRANCH="${{ inputs.release-branch }}"
    SNAPSHOT_BRANCH="${{ inputs.snapshot-branch }}"

    echo "Branch          : $BRANCH"
    echo "Release branch  : $RELEASE_BRANCH"
    echo "Snapshot branch : $SNAPSHOT_BRANCH"
    echo "Version         : $VERSION"

    # Release branch → release versions only
    if [[ "$BRANCH" == "$RELEASE_BRANCH" && "$VERSION" == *SNAPSHOT ]]; then
      echo "❌ SNAPSHOT versions are not allowed on release branch ($RELEASE_BRANCH)"
      exit 1
    fi

    # Snapshot branch → SNAPSHOT versions only
    if [[ "$BRANCH" == "$SNAPSHOT_BRANCH" && "$VERSION" != *SNAPSHOT ]]; then
      echo "❌ Release versions are not allowed on snapshot branch ($SNAPSHOT_BRANCH)"
      exit 1
    fi

    # Other branches → no deploy
    if [[ "$BRANCH" != "$RELEASE_BRANCH" && "$BRANCH" != "$SNAPSHOT_BRANCH" ]]; then
      echo "❌ Deployment is allowed only from '$RELEASE_BRANCH' or '$SNAPSHOT_BRANCH'"
      exit 1
    fi

    

