name: Build and Update Dockerfile

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
        type: string
      serviceType:
        description: 'Select service type (Core or Extension)'
        required: true
        type: choice
        options:
          - core
          - extension
      microservice:
        description: 'Select microservice to build'
        required: true
        type: choice
        options:
          - service1
          - service2
          - service3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Set application name based on serviceType and microservice
      - name: Set Application Name
        id: set-app-name
        run: echo "APP_NAME=myapp-${{ inputs.serviceType }}-${{ inputs.microservice }}" >> $GITHUB_ENV

      # Update Dockerfile with new application name
      - name: Update Dockerfile with Application Name
        run: |
          sed -i "s/APP_NAME_PLACEHOLDER/${{ env.APP_NAME }}/g" path/to/Dockerfile

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.APP_NAME }} .
