name: Build Microservices

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'develop'
        type: string
      serviceType:
        description: 'Select service type (Core or Extension)'
        required: true
        type: choice
        options:
          - core
          - extension
      microservice:
        description: 'Select microservice to build'
        required: true
        type: choice
        options:
          - service1
          - service2
          - service3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Get Commit SHA
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "Short Commit ID: $SHORT_SHA"

      - name: Add version to workflow summary
        run: |
          VERSION=$(cat version.txt)
          echo "## Version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Core Microservices
      - name: Build core microservice 1
        if: ${{ inputs.serviceType == 'core' && inputs.microservice == 'service1' }}
        run: |
          cd core/service1
          ./mvnw clean install

      - name: Build core microservice 2
        if: ${{ inputs.serviceType == 'core' && inputs.microservice == 'service2' }}
        run: |
          cd core/service2
          ./mvnw clean install

      - name: Build core microservice 3
        if: ${{ inputs.serviceType == 'core' && inputs.microservice == 'service3' }}
        run: |
          cd core/service3
          ./mvnw clean install

      # Extension Microservices
      - name: Build extension microservice 1
        if: ${{ inputs.serviceType == 'extension' && inputs.microservice == 'service1' }}
        run: |
          cd extensions/service1
          ./mvnw clean install

      - name: Build extension microservice 2
        if: ${{ inputs.serviceType == 'extension' && inputs.microservice == 'service2' }}
        run: |
          cd extensions/service2
          ./mvnw clean install

      - name: Build extension microservice 3
        if: ${{ inputs.serviceType == 'extension' && inputs.microservice == 'service3' }}
        run: |
          cd extensions/service3
          ./mvnw clean install
