name: Build Microservices

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'develop'
        type: string
      microservice:
        description: 'Microservice to build'
        required: true
        type: choice
        options:
          - service1
          - service2
          - service3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build microservice 1
        if: ${{ inputs.microservice == 'service1' }}
        run: |
          cd microservices/service1
          ./mvnw clean install

      - name: Build microservice 2
        if: ${{ inputs.microservice == 'service2' }}
        run: |
          cd microservices/service2
          ./mvnw clean install

      - name: Build microservice 3
        if: ${{ inputs.microservice == 'service3' }}
        run: |
          cd microservices/service3
          ./mvnw clean install
